name: Dependencies

on:
  workflow_dispatch

jobs:
  vcpkg:
    strategy:
      matrix:
        os: [[windows-latest,x64-windows], [macos-latest,x64-osx]]
        buildType: [Release]
    runs-on: ${{ matrix.os[0] }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '11cbb6b57b502d4864fa3c51b36b1ec88527a036'
        setupOnly: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.buildType }}

    - name: Install necessary packages
      shell: bash
      working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
      run: $VCPKG_ROOT/vcpkg install --clean-buildtrees-after-build

  vcpkg-linux:
    strategy:
      matrix:
        os: [[ubuntu-latest,x64-linux]]
        buildType: [Release]
    runs-on: ${{ matrix.os[0] }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '11cbb6b57b502d4864fa3c51b36b1ec88527a036'
        setupOnly: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.buildType }}

    - name: Install necessary packages
      shell: bash
      working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
      run: $VCPKG_ROOT/vcpkg install --clean-buildtrees-after-build
